server:
  port: 8080

spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      routes:
        # Authentication service routes
        - id: users-auth-public
          uri: lb://microservice-users-authentification
          predicates:
            - Path=/auth/login,/reset-password/**
          order: -1
        - id: users-auth-admin
          uri: lb://microservice-users-authentification
          predicates:
            - Path=/admin/**
          order: -1
        - id: users-auth-profile
          uri: lb://microservice-users-authentification
          predicates:
            - Path=/profile/**
          order: -1
        - id: users-auth-roles
          uri: lb://microservice-users-authentification
          predicates:
            - Path=/roles,/roles/**
          order: -1
        - id: users-auth-photo
          uri: lb://microservice-users-authentification
          predicates:
            - Path=/photo-de-profil/**
          order: -1
        - id: users-auth-members
          uri: lb://microservice-users-authentification
          predicates:
            - Path=/api/membres,/api/membres/**
          order: -1
        # Project core service routes
        - id: project-core-projet-membres
          uri: lb://project-core-service
          predicates:
            - Path=/api/projet-membres,/api/projet-membres/**
          order: 0
        - id: project-core-partie-prenantes
          uri: lb://project-core-service
          predicates:
            - Path=/api/partie-prenantes,/api/partie-prenantes/**
          order: 0
        - id: project-core-projets
          uri: lb://project-core-service
          predicates:
            - Path=/api/projets,/api/projets/**
          order: 0
        - id: project-core-activites
          uri: lb://project-core-service
          predicates:
            - Path=/api/activites,/api/activites/**
          order: 0
        - id: project-core-documents
          uri: lb://project-core-service
          predicates:
            - Path=/api/documents,/api/documents/**
          order: 0
        # Default route for authentication service
        - id: users-auth-default
          uri: lb://microservice-users-authentification
          predicates:
            - Path=/**
          order: 100
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedHeaders: "*"
            allowedMethods:
              - POST
              - GET
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowCredentials: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.netflix.discovery: DEBUG
    com.netflix.eureka: DEBUG

eureka:
  instance:
    hostname: api-gateway
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
    healthcheck:
      enabled: true