server:
  port: 8080

spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      routes:
        # Endpoints accessibles sans authentification
        - id: users-auth-public
          uri: http://microservice-users-authentification:8081
          order: -1
          predicates:
            - Path=/auth/login, /auth/login/**
            - Path=/reset-password/**
        # Endpoints réservés au rôle ADMINISTRATEUR
        - id: users-auth-admin
          uri: http://microservice-users-authentification:8081
          predicates:
            - Path=/admin/**
        # Endpoints nécessitant une authentification
        - id: users-auth-profile
          uri: http://microservice-users-authentification:8081
          predicates:
            - Path=/profile/**
        # Toutes les autres requêtes nécessitent une authentification
        - id: users-auth-default
          uri: http://microservice-users-authentification:8081
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - POST
              - GET
              - PUT
              - DELETE
              - PATCH

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/