server:
  port: 8080

spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: users-auth
          uri: lb://microservice-users-authentification
          predicates:
            - Path=/auth/**, /reset-password/**, /profile/**, /admin/**, /missions/**
        - id: projects-service
          uri: lb://microservice-projets
          predicates:
            - Path=/api/projects/**, /api/templates/**, /api/etapes-**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"

eureka:
  instance:
    hostname: api-gateway
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
    healthcheck:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG