server:
  port: 8080

spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      routes:
        # Authentication service routes
        - id: users-auth-public
          uri: http://microservice-users-authentification:8081
          order: -1
          predicates:
            - Path=/auth/login,/reset-password/**
        - id: users-auth-missions
          uri: http://microservice-users-authentification:8081
          order: -1
          predicates:
            - Path=/missions/**
        - id: users-auth-admin
          uri: http://microservice-users-authentification:8081
          predicates:
            - Path=/admin/**,/admin/equipes/**
        - id: users-auth-profile
          uri: http://microservice-users-authentification:8081
          predicates:
            - Path=/profile/**
        - id: users-auth-default
          uri: http://microservice-users-authentification:8081
          predicates:
            - Path=/**

        # Project service routes
        - id: projects-route
          uri: http://microserviceprojets:8082
          predicates:
            - Path=/api/projects/**
        - id: templates-route
          uri: http://microserviceprojets:8082
          predicates:
            - Path=/api/templates/**
        - id: etapes-projet-route
          uri: http://microserviceprojets:8082
          predicates:
            - Path=/api/etapes-projet/**
        - id: etapes-template-route
          uri: http://microserviceprojets:8082
          predicates:
            - Path=/api/etapes-template/**
        - id: projets-route
          uri: http://microserviceprojets:8082
          predicates:
            - Path=/api/projets/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedHeaders: "*"
            allowedMethods:
              - POST
              - GET
              - PUT
              - DELETE
              - PATCH
  devtools:
    restart:
      enabled: true
      livereload:
        enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

eureka:
  instance:
    hostname: api-gateway
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
    healthcheck:
      enabled: true