#config-service
server:
  port: 8888  # Le Config Service tourne sur le port 8888

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          # Chemin local vers le dépôt contenant les fichiers de config
          uri: https://github.com/saraaj16/cloud-confi.git
          clone-on-start: true
  devtools:
    restart:
        enabled: true
        livereload:
          enabled: true


eureka:
  instance:
    hostname: config-service
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
    healthcheck:
      enabled: true