#config-service
server:
  port: 8888  # Le Config Service tourne sur le port 8888

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          # Chemin local vers le dépôt contenant les fichiers de config
          uri: https://github.com/saraaj16/cloud-confi.git
          clone-on-start: true

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
    client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://eureka-0.eureka.default.svc.cluster.local:eureka/eureka
