server:
  port: 8761  # Port par défaut de Eureka Server

spring:
  application:
    name: discovery-service
    cloud:
      config:
        enabled: true
        uri: http://localhost:8888  # Adresse du Config Server

eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: true  # Auto-préservation activée
  client:
    register-with-eureka: false     # Le serveur ne s’enregistre pas lui-même
    fetch-registry: false

