server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    enableSelfPreservation: false # Optional: Disable self-preservation for local development

logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG