#discovery-service
server:
  port: 8761  # Port par défaut de Eureka Server

spring:
  application:
    name: discovery-service
  devtools:
    restart:
        enabled: true
        livereload:
          enabled: true

eureka:
  instance:
    hostname: "${HOSTNAME}.eureka"
  server:
    enable-self-preservation: true  # Auto-préservation activée
  client:
    register-with-eureka: false     # Le serveur ne s’enregistre pas lui-même
    fetch-registry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS}
