server:
  port: 8082

spring:
  application:
    name: microserviceprojets
  datasource:
    url: jdbc:oracle:thin:@host.docker.internal:1521:XE
    username: C##MICROPROJET
    password: sara
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: Saraaitelhaj93@gmail.com
    password: vgznulowgulssbww
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cloud:
    config:
      uri: http://config-service:8888
      enabled: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

user:
  service:
    url: http://microservice-users-authentification:8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: microserviceprojets
    preferIpAddress: false

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: info
    org.springframework.web: info
    ma.inwi: debug