server:
  port: 8082

spring:
  application:
    name: microserviceprojets

  mail:
    host: smtp.gmail.com
    port: 587
    username: "Saraaitelhaj93@gmail.com"
    password: "vgznulowgulssbww"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  devtools:
    restart:
      enabled: true
      livereload:
        enabled: true

  datasource:
    url: "jdbc:oracle:thin:@host.docker.internal:1521:XE"
    username: "C##MICROPROJET"
    password: "sara"
    driver-class-name: "oracle.jdbc.OracleDriver"

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        default_batch_fetch_size: 20

  main:
    allow-circular-references: true
  data:
    web:
      pageable:
        default-page-size: 10
      rest:
        pageSerializationMode: VIA_DTO

management:
  endpoints:
    web:
      exposure:
        include: beans, health, info
  endpoint:
    health:
      show-details: always

jwt:
  secret: L5dyHWlg3wwlRJH5dpI+9eGBkQH/W/ZyeR3EwCdaJioBix86eVktAc9TVC/j/z2VVw9JnWFjR5YtT/F7KqHoDA==
  expiration: 86400000 # 1 jour en millisecondes
  header: Authorization
  prefix: Bearer

eureka:
  instance:
    hostname: microserviceprojets
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
    healthcheck:
      enabled: true

logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.cloud: DEBUG
    root: error
    org.springframework: error
    org.springframework.security: DEBUG
    ma.inwi.microserviceprojets: DEBUG

user-service:
  url: http://microservice-users-authentification:8081

