spring:
  application:
    name: microservice-workflow

server:
  port: 8082

  datasource:
    url: "jdbc:oracle:thin:@host.docker.internal:1521:XE"
    username: "C##MICROWORKFLOW"
    password: "sara"
    driver-class-name: "oracle.jdbc.OracleDriver"

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: "Saraaitelhaj93@gmail.com"
    password: "vgznulowgulssbww"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: beans, health,info
  endpoint:
    health:
      show-details: always

jwt:
  secret: "TmJLS8mnj7T81MOKdTIy/NZ5NzXl3JCfJNFw8+eK3meb/hcM02FNZApHxRJv+Z75ss2H4u8RjZdxJdFKbfyDog=="
  expiration: 86400000 # 1 jour en millisecondes
  header: Authorization
  prefix: Bearer

logging:
  level:
    org.springframework: DEBUG
    org.springframework.beans.factory: TRACE
    org.springframework.context.annotation: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/


user:
  service:
    url: http://microservice-users-authentification:8081
