server:
  port: 8081

spring:
  application:
    name: project-service
  datasource:
    url: "jdbc:oracle:thin:@localhost:1521:XE"
    username: "C##MICROAUTH"
    password: "sara"
    driver-class-name: "oracle.jdbc.OracleDriver"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

# Configuration for JWT
jwt:
  secret: "TmJLS8mnj7T81MOKdTIy/NZ5NzXl3JCfJNFw8+eK3meb/hcM02FNZApHxRJv+Z75ss2H4u8RjZdxJdFKbfyDog=="
  expiration: 86400000 # 24h in milliseconds

# Auth service configuration
auth-service:
  base-url: http://localhost:8080