#microserviceprojets
server:
  port: 8082

spring:
  application:
    name: microserviceprojets

  datasource:
    url: "jdbc:oracle:thin:@localhost:1521:XE"

    username: "C##MICROPROJET"
    password: "sara"
    driver-class-name: "oracle.jdbc.OracleDriver"

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        default_batch_fetch_size: 20

  main:
    allow-circular-references: true
  data:
    web:
      pageable:
        default-page-size: 10
      rest:
        pageSerializationMode: VIA_DTO



management:
  endpoints:
    web:
      exposure:
        include: beans, health,info
  endpoint:
    health:
      show-details: always


