#microservice-users-authentification
server:
  port: 8081

spring:
  application:
    name: microservice-users-authentification
    upload-dir: "C:/Users/Swerera's laptop/Desktop/PFE/pilotage_backend/photo-de-profil"

  datasource:
    url: "jdbc:oracle:thin:@host.docker.internal:1521:XE"
    username: "C##MICROAUTH"
    password: "sara"
    driver-class-name: "oracle.jdbc.OracleDriver"

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true


  web:
    resources:
      static-locations: file:${user.profile.photo.upload-dir}/
  main:
    allow-circular-references: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: "Saraaitelhaj93@gmail.com"
    password: "vgznulowgulssbww"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  devtools:
    restart:
        enabled: true
        livereload:
          enabled: true

user:
  profile:
    photo:
      upload-dir: file:///C:/Users/Swerera's%20laptop/Desktop/PFE/pilotage_backend/photo-de-profil/

management:
  endpoints:
    web:
      exposure:
        include: beans, health, info
  endpoint:
    health:
      show-details: always

jwt:
  secret: "TmJLS8mnj7T81MOKdTIy/NZ5NzXl3JCfJNFw8+eK3meb/hcM02FNZApHxRJv+Z75ss2H4u8RjZdxJdFKbfyDog=="
  expiration: 86400000 # 1 jour en millisecondes
  header: Authorization
  prefix: Bearer

logging:
  level:
    root: error
    org.springframework: error
    ma.inwi.microserviceusersauthentification: error

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


