#microservice-users-authentification
server:
  port: 8081

spring:
  application:
    name: microservice-users-authentification

  datasource:
    url: "jdbc:oracle:thin:@host.docker.internal:1521:XE"
    username: "C##MICROAUTH"
    password: "sara"
    driver-class-name: "oracle.jdbc.OracleDriver"

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true


  web:
    resources:
      static-locations: file:${user.profile.photo.upload-dir}/
  main:
    allow-circular-references: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: "Saraaitelhaj93@gmail.com"
    password: "vgznulowgulssbww"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  devtools:
    restart:
        enabled: true
        livereload:
          enabled: true

user:
  profile:
    photo:
      upload-dir: "C:/Users/Swerera's laptop/Desktop/PFE/pilotage_backend/photo-de-profil"
  service:
    url: http://microservice-users-authentification:8080

management:
  endpoints:
    web:
      exposure:
        include: beans, health, info
  endpoint:
    health:
      show-details: always

jwt:
  secret: L5dyHWlg3wwlRJH5dpI+9eGBkQH/W/ZyeR3EwCdaJioBix86eVktAc9TVC/j/z2VVw9JnWFjR5YtT/F7KqHoDA==
  expiration: 86400000 # 1 jour en millisecondes
  header: Authorization
  prefix: Bearer

logging:
  level:
    root: error
    org.springframework: error
    ma.inwi.microserviceusersauthentification: error

eureka:
  instance:
    hostname: microservice-users-authentification
    preferIpAddress: false
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
    healthcheck:
      enabled: true

