# Ce fichier porte le même nom que spring.application.name (project-core-service.yml).

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: "Saraaitelhaj93@gmail.com"
    password: "vgznulowgulssbww"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  datasource:
    url: "jdbc:oracle:thin:@host.docker.internal:1521:XE"
    username: "C##MICROPROJET"
    password: "sara"
    driver-class-name: "oracle.jdbc.OracleDriver"

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        default_batch_fetch_size: 20

  main:
    allow-circular-references: true

  data:
    web:
      pageable:
        default-page-size: 10
    rest:
      pageSerializationMode: VIA_DTO

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json

management:
  endpoints:
    web:
      exposure:
        include: beans, health, info
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    hostname: project-core-service
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
    healthcheck:
      enabled: true

logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.cloud: DEBUG
    root: ERROR
    org.springframework.security: DEBUG
    ma.inwi.projectcoreservice: DEBUG
